Repository Lima-Almeida/PlataformaFin, pull requests merged in 2024-12, with the labels that each got.

#36 correçao code-smells cadastro
  lib/views/components/constants.dart
  lib/views/pages/cadastro.dart
  pubspec.lock
Labels: AvaliacaoA4

#37 correçao logica BD e add menu
  lib/models/categoria.dart
  lib/views/pages/cadastroCategoria.dart
  lib/views/pages/cadastroReceitas.dart
  lib/views/pages/categoriasView.dart
  lib/views/pages/login.dart
Labels: Avaliação A3

#38 atualizaçao drawerMenu e navegacao
  lib/models/services/logout.dart
  lib/views/pages/cadastroCategoria.dart
  lib/views/pages/cadastroReceitas.dart
  lib/views/pages/metas.dart
  lib/widgets/drawer_menu.dart
Labels: Avaliação A3

#39 Feature/categorias
  lib/views/pages/cadastroCategoria.dart
  lib/views/pages/cadastroReceitas.dart
Labels: Avaliação A3

#44 Testes automatizados
  lib/views/pages/cadastro.dart
  lib/views/pages/cadastroReceitas.dart
  pubspec.lock
  resultado_teste.txt
  test/cadastro_test.dart
  test/login_test.dart
Labels: Avaliação A5

#46 adicionei uma pagina de relatorios financeiros
  lib/views/pages/metas.dart
  lib/views/pages/relatorios.dart
  lib/widgets/drawer_menu.dart
Labels: Avaliação A3

#47 coluna foi retirada
  lib/views/pages/relatorios.dart
Labels: Avaliação A3
